# Generated by Django 2.2.6 on 2019-12-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='session_key',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
